version: '3'
services:
    mongodb:
        image: mongo:jammy
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root 
            - MONGO_INITDB_ROOT_PASSWORD=mongo 
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root 
            - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo   